---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: colors
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - color: blue
          - color: red
          - color: green
  template:
    metadata:
      name: colors-{{color}}
    spec:
      destination:
        namespace: colors
        server: https://kubernetes.default.svc
      project: product
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          enabled: true
          selfHeal: true
          prune: true
      source:
        path: .
        repoURL: oci://docker.io/ecklm/colors-demo-app
        targetRevision: 1.1.0
        helm:
          valuesObject:
            color: "{{color}}"
            ingress:
              host: "{{color}}.project-x.sbx.ecklm.az.cubix-pe.hu"
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
